name: ESLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint updated JavaScript files with ESLint

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get changed files
        id: getfile
        run: echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: Install ESLint
        run: npm install eslint

      - name: Lint changed files using ESLint
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
            echo "file $i"
            if [[ "$i" == *".js" ]]
            then
              echo "linting $i"
              npx eslint $i
            fi
          done
