name: Super-Linter

# Triggers the workflow on push or pull request events only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint updated JavaScript files

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false # VALIDATE_JAVASCRIPT_ES is desired (true by default)
          VALIDATE_JSCPD: false
